default_language_version:
  python: python
repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [.]
        pass_filenames: false
    language_version: python3.6
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.15
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
      - id: pylama
        additional_dependencies:
          - mccabe
          - pycodestyle
          - pyflakes
          - radon
        args: ['-o', './api/pylama.ini']
  - repo: https://github.com/PyCQA/bandit
    # TODO: Change rev from master to pinned version. In latest version (1.5.1) file .pre-commit-hooks.yaml is absent.
    rev: master
    hooks:
      - id: bandit
        args: ['-r', './api']
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
