version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          name: DEPLOY - Add SSH keys
          fingerprints:
            - fc:94:ff:15:c7:84:2d:fd:23:bc:41:99:68:5c:2c:c4
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          command: |
            cp .env.default .env
            yarn install --ignore-engines
            CI=false yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: |
            ./deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - v3_develop
                - v3_stable
