[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | splinter-tests
  | migrations
)/
'''

[tool.isort]
combine_star = true
from_first = false
include_trailing_comma = true
indent = '    '
known_third_party = 'django,rest_framework'
length_sort = false
line_length = 120
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 5
sections = 'FUTURE,STDLIB,DJANGO,DRF,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
skip_glob = '*migrations/*.py,splinter-tests/*'
use_parentheses = true
